version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-tarefa
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tarefa_db
      MYSQL_USER: rm560907
      MYSQL_PASSWORD: fiap2026
    ports:
      - "3306:3306"
    volumes:
      - mysql-tarefa-volume:/var/lib/mysql
    networks:
      - tarefa-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "rm560907", "-pfiap2026"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: api-tarefa:v1
    container_name: api-tarefa
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/tarefa_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: rm560907
      SPRING_DATASOURCE_PASSWORD: fiap2026
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    networks:
      - tarefa-network

volumes:
  mysql-tarefa-volume:

networks:
  tarefa-network:
    driver: bridge